[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.12"
dependencies = [
    "aiohttp<3.14",
    "alembic>=1.19.1",
    "fastapi[standard]>=0.141.1",
    "httpx>=0.28.1",
    "limits>=5.8.0",
    "pwdlib[argon2]>=0.3.0",
    "pydantic-settings>=2.15.0",
    "pytest>=9.1.1",
    "python-decouple>=3.8",
    "sqlalchemy>=2.0.51",
]

[dependency-groups]
dev = [
    "aioresponses>=0.7.9",
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
]
